services:
  localstack:
    container_name: 'encryption_app_localstack'
    image: localstack/localstack
    ports:
      - '127.0.0.1:4566:4566' # LocalStack Gateway
      - '127.0.0.1:4510-4559:4510-4559' # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
      - EXTRA_CORS_ALLOWED_ORIGINS=http://localhost:5173,http://127.0.0.1:8000
    volumes:
      - './volumes/localstack:/var/lib/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      - encryption-app-network
  
  postgres:
    container_name: encryption_app_postgres
    image: postgres:15.3-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    networks:
      - encryption-app-network
      
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: encryption_app_pgadmin
    restart: always
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PASSWORD}
    ports:
      - '8090:80'
    volumes:
      - ./volumes/pgadmin:/var/lib/pgadmin
    networks:
      - encryption-app-network
